brave/sync

README.md
client/config.js
client/constants/messages.js
client/init.js
client/polyfill/chrome.js
client/sync.js
package.json
yarn.lock

to test:
1. checkout https://github.com/brave/browser-laptop/tree/feature/syncing
2. in sync, do `npm run dist` to build the sync client and copy it over to browser-laptop
3. in browser-laptop, `npm start` and look for any errors in `Library/Application Support/brave-development/chrome-debug.log`

make sync integrate into browser-laptop

---

.travis.yml
client/requestUtil.js
package.json
server/config/custom-environment-variables.json
server/config/default.json
server/config/test.json
server/users.js
test/client/requestUtil.js
test/client/testHelper.js
test/server/users.js
test/testHelper.js
yarn.lock

Tests: client can instantiate requestUtil

---

client/requestUtil.js
lib/radix64.js
lib/s3Helper.js
test/s3Helper.js
test/server/lib/user-aws-s3-post-authenticator.js

Extract S3 methods from requestUtil to s3Helper

---

client/constants/messages.js
client/requestUtil.js
client/sync.js
yarn.lock

also does some refactoring so that clientSerializer and requester are not
global vars
fix #15

add IPC entry points to delete user/category

---

lib/crypto.js

testing if this passes travis for some reason. same change as #35
:crystal_ball:

Use public interface to get signing seed length

---

client/recordUtil.js
lib/api.proto.js
package.json
yarn.lock

yarn upgrade then running the `pbjs` CLI installs packages then fails, but when you run it again it works.

Upgrade protobuf.js to 6.5

---

lib/api.proto
lib/api.proto.js
test/client/recordUtil.js
yarn.lock

To support #55 
Test plan: make sure tests pass

Remove Bookmark.index; add prev and next objectIds

---

client/recordUtil.js
client/sync.js

merge staging

---

client/recordUtil.js
test/client/recordUtil.js

instead of just the changed props
fix #95

Send entire sync record for history and bookmark RESOLVED_SYNC_RECORDS

---

.travis.yml

https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2

Fix travis for trusty changes 2017-06-21

---

client/config.js
client/constants/messages.js
client/init.js

Needed for https://github.com/brave/sync/issues/128

Emit brave/sync version with GET_INIT_DATA

---

client/requestUtil.js
server/lib/user-aws-credential-generator.js

To prevent users from mucking with each others' data.

Use namespaced SNS and SQS

---

client/requestUtil.js
server/lib/request-verifier.js
server/lib/user-aws-s3-bucket-configuration.js
server/users.js
test/server/lib/user-aws-s3-bucket-configuration.js

Fixes multiple bucket notifications issue.

Bucket multiple notifications fix

---

server/index.js

Fixes multiple bucket notifications issue. It's related to that issue https://github.com/brave/sync/issues/192

CORS for bucket notification

---

client/config.js

Add error message for expired token

---

package-lock.json

'npm audit' was failing
needed for https://github.com/brave/brave-browser/pull/2382

Auto fix some npm audit errors

---

package-lock.json

this is the merge commit from https://github.com/brave/sync/pull/257

fix deps vulnerabilities (master branch)

---

package-lock.json

lock `merge`@1.2.1 pkg in package-lock.json
related to https://github.com/brave/sync/pull/259

lock `merge`@1.2.1 pkg in package-lock.json

---

package-lock.json
package.json

follow-up of https://github.com/brave/sync/pull/262

Update tape run (master)

---

client/requestUtil.js
client/sync.js
lib/s3Helper.js
test/client/requestUtil.js

Objects in chunks

---

package-lock.json

fix https://github.com/brave/sync/issues/292

Issue 292: Updating js-yaml to fix audit errors

---

package-lock.json

Helps fix brave/brave-browser#4075

Fix vulnerability preventing Desktop from building

---

package-lock.json
package.json

fix #262 and update uglify to the currently maintained package

Fix tape security issue

---

client/recordUtil.js

We met the situation when [CREATE, UPDATE] were merged to [CREATE], which was then ignored because local object had been existed.
This PR makes CREATE and DELETE records stays alone to prevent such ignoring. So only UPDATE records of the same object id are merged.
STR for brave-core brave-syncer branch:
1) DeviceA: create folderA in bookmarks
2) DeviceA: create bookmarks of brave://bookmarks, brave://sync, brave://inspect, all in `Bookmarks Bar` folder
3) DeviceA: enable sync and copy code words
4) DeviceB: join sync chain with words from pt.3
5) DeviceB: As soon as bookmarks from DeviceA appear , move 3 bookmarks into folderA
6) Actual on DeviceA: bookmark will not be moved
Expected on DeviceA: bookmarks should be moved.

Merge by id action master

---

package-lock.json
package.json

Fix https://github.com/brave/sync/issues/309

Update deprecated uglifyjs

---

package-lock.json

Update dependency for set-value and mixin-deep

---

lib/s3Helper.js
test/client/requestUtil.js
test/s3Helper.js

Ignore records from SQS which where seen in S3
Uplift of https://github.com/brave/sync/pull/306 to master

Ignore records from SQS which where seen in S3 (master)

---

client/requestUtil.js
lib/s3Helper.js
test/client/requestUtil.js

Create separate queues for preferences records
This is an uplift of https://github.com/brave/sync/pull/331 into master.

Create separate queues for preferences records (Uplift to master)

---

package-lock.json
package.json
server/config/custom-environment-variables.json
server/config/default.json
server/config/production.json
server/lib/util.js
server/redis.js
server/users.js
test/server/lib/util.js

fix https://github.com/brave/sync/issues/343

instrument dau by way of redis hyperloglog

---

server/lib/util.js
test/server/lib/util.js

Dau ios touchup

---

client/constants/messages.js
client/requestUtil.js
client/sync.js
lib/s3Helper.js
package-lock.json
package.json
test/client/requestUtil.js

original PR https://github.com/brave/sync/pull/350

Compaction API (master)

---

client/constants/messages.js
client/sync.js

merged staging PR https://github.com/brave/sync/pull/358

Add SENT_SYNC_RECORDS which is the callback of SEND_SYNC_RECORDS (master)

---

package-lock.json
package.json

Helps to fix brave/brave-browser#8722

Introduce `npm-force-resolutions` dependency to help resolve npm audit vulnerabilities

---

package-lock.json
package.json

- removed `package-lock.json`
- made `tape-run` optional

Manual cherry-pick of https://github.com/brave/sync/pull/379
