brave/sync

lib/api.proto
lib/serializer.js
package.json
server/config/custom-environment-variables.json
server/config/default.json
server/index.js
server/lib/request-verifier.js
server/lib/user-aws-s3-post-authenticator.js
server/users.js
test/crypto.js
test/serializer.js
test/server/lib/request-verifier.js
test/server/lib/user-aws-credential-generator.js
test/server/lib/user-aws-s3-post-authenticator.js
test/server/users.js
yarn.lock

- Adds `request-verifier` which verifies signed timestamp in request bodies.
- Uses `request-verifier` to verify requests to `POST /{userId}/credentials`.
auditors: @diracdeltas

server: require signed requests

---

client/bundle.js
client/requestUtil.js
client/sync.js
lib/api.proto
lib/serializer.js
server/lib/user-aws-credential-generator.js
server/lib/user-aws-s3-post-authenticator.js
server/users.js
test/serializer.js
test/server/lib/user-aws-credential-generator.js
test/server/lib/user-aws-s3-post-authenticator.js
test/server/users.js

- Server returns s3 bucket and aws region.
- requestUtil uses the bucket when instantiating Aws.S3
- client saves region but doesn't use it (yet).

Server returns AWS region and S3 bucket

---

.travis.yml

travis browsertests
I couldn't figure out how to add browsertest to coverage, but we'll still get coverage on `tape test/**/*.js`.
Auditors: @diracdeltas

Travis: Add browsertest

---

client/requestUtil.js
client/sync.js
lib/api.proto
lib/s3Helper.js
lib/serializer.js
package.json
server/lib/user-aws-credential-generator.js
server/lib/util.js
server/users.js
test/client/requestUtil.js
test/client/testHelper.js
test/s3Helper.js
test/serializer.js
test/server/lib/user-aws-s3-post-authenticator.js
test/server/users.js
test/testHelper.js
yarn.lock

Fix, Test requestUtil prefs/device; add helpers

---

README.md
client/config.js
client/cryptoUtil.js
client/requestUtil.js
client/sync.js
test/client/requestUtil.js
test/client/testHelper.js
test/server/lib/user-aws-credential-generator.js
test/server/users.js

- Extract encrypt() and decrypt() from sync.js into cryptoUtil.js
- Extract refreshAWSCredentials() from sync.js into requestUtil.js
- requestUtil automatically detects expired credentials and requests new ones from the server

Auto refresh AWS credentials

---

package.json
yarn.lock

Fix #16 
- `yarn build` bundle.js is now 1.35 MB (was 3.03 MB)
- browser tests include uglifyjs but without --mangle
Notes:
- source map (og -> browserify -> uglify) was too much effort
- uglifyjs --compress not used; it takes more time, might be weird and saves only 20K

Add uglifyjs2 #harmony

---

client/recordUtil.js
client/sync.js
lib/api.proto.js
lib/serializer.js
package.json
test/client/recordUtil.js
test/serializer.js
yarn.lock

Fix #6 
1. Ensures SyncRecord IPC message compatibility.
2. Upgrades protobuf.js to 6.4.5 and converts api.proto to static JS code.
- Proto: With classes as static code you can't use reflection e.g. `SyncRecord.lookup('Site')`. This is minor beause you'd just do `SyncRecord.Site`.
- Proto: `oneof` attributes have issues, notably SyncRecord .objectData is stuck as "bookmark". As a workaround I made a helper: serializer.getSyncRecordObjectData()
Test plan for (1):
- `yarn dist` to browser-laptop `#feature/syncing`
- Go to [browser-laptop app/sync.js#L236](https://github.com/brave/browser-laptop/blob/feature/syncing/app/sync.js#L236); change RECEIVE_SYNC_RECORDS to GET_EXISTING_OBJECTS and add `console.log(records)`.
- Start browser-laptop and visit any URL to make a historySite.
- Look at …

Protobuf.JS 6.45; SyncRecord as JS object

---

client/recordUtil.js
lib/api.proto
lib/api.proto.js
lib/serializer.js
test/client/recordUtil.js

Currently you can't encode a siteSetting with just a single setting . For example, a SyncRecord with `siteSetting: {shieldsUp: true}` encoded and decoded returns additionally *all* the siteSetting fields's defaults. This is because proto3 doesn't distinguish between fields set to default values and unset fields.
This PR adds the `SyncRecord.siteSetting.fields` with which we'll specify the changed fields. This is similar to [google.protobuf.Fieldmask](https://github.com/dcodeIO/protobuf.js/blob/master/google/protobuf/field_mask.proto).
recordUtil.syncRecordAsJS() will take `fields` into account when converting records back to the browser client format.

Add SyncRecord.siteSetting.fields

---

README.md

Since you already have a yarn.lock, it seems to make sense to encourage devs to use exactly the same deps. And while we are at it, why not use yarn consistently for everything?

Use yarn instead of npm

---

client/requestUtil.js
test/s3Helper.js

Fix #53
This uses 3 bytes per S3 key, however with multi-part records we still support up to ~50 KiB per record.

Use ms precision for record timestamps in S3 key 

---

client/constants/messages.js
client/requestUtil.js
client/sync.js
lib/s3Helper.js
test/client/requestUtil.js

Fix #68 
browser/lib API changes:
- FETCH_SYNC_RECORDS
- New param: `limitResponse` (boolean). when set to true, limits response to 1000 (previously unbounded)
- New response param: `lastRecordTimestamp` (number), the timestamp in milliseconds of the last record in a response batch. Useful as a cursor for traversing batches of 1000.
- Changes should be non-breaking and compatible with existing browser Sync implementations.
Test plan:
1. brave/sync tests should pass
2. `yarn dist` into browser-laptop
3. browser-laptop sync tests should pass (`yarn test -- --grep='"^Syncing"'`)

FETCH_SYNC_RECORDS can limit response to 1000 records

---

client/constants/messages.js
client/requestUtil.js
client/sync.js

to support #41
Browser requests FETCH_SYNC_DEVICES when toggling sync from off -> on
It's a rebranded FETCH_SYNC_RECORDS which returns device records from all time (responses go through the existing down stream, GET_EXISTING_OBJECTS etc)

Add FETCH_SYNC_DEVICES to get all device records

---

client/constants/messages.js
client/sync.js
lib/s3Helper.js
test/client/requestUtil.js

mostly for serg to know when to stop getting the initial sync records
also sends GET_EXISTING_OBJECTS and RESOLVED_SYNC_RECORDS regardless of whether records is empty, as joel requested
fix #72

add isTruncated parameter to GET_EXISTING_OBJECTS

---

client/sync.js

Fix #75
Auditors: @diracdeltas
Test plan:
0. First confirm it's broken on master:
a. Start browser-laptop with a new profile.
b. Enable Sync
c. Visit archive.org and disable shields.
d. Visit wikipedia.org and disable shields.
e. Restart Brave.
f. Console shows 3 devices / 2 too many:
```
sync 1492637047413: fetching BOOKMARKS,PREFERENCES records after 1492637031
sync 1492637047761: fetched 3 devices
sync 1492637047871: fetched 3 PREFERENCES after 1492637031
```
g. Restart Brave.
h. Console shows again 3 devices:
```
sync 1492637059167: fetching devices
sync 1492637059196: fetching BOOKMARKS,PREFERENCES records after 1492637047
sync 1492637059559: fetched 3 devices
```
i. Close Brave.
1. Go to brave/sync, checkout this branch fix/list-devices and yarn dist.
2. Restart Brave on the …

FETCH_SYNC_DEVICES should return only devices

---

client/recordUtil.js

The previous way somtimes merged a record into record with a different objectId somehow. Using Object.values guarantees that the final number of merged records will be the same as the number of unique objectIds.
Fix https://github.com/brave/browser-laptop/issues/8454, fix tests in https://github.com/brave/browser-laptop/pull/8480
Test plan:
1. Sync to the 'rummy tarp...' group sent by slack DM.
2. You should see a bookmark folder 'f1' with two bookmarks in it; previously the bookmarks would be at the top level.
3. checkout https://github.com/brave/browser-laptop/pull/8480 and run "npm run test -- --grep='^Syncing bookmarks'". the tests should pass.

Fix record merging

---

client/constants/messages.js
client/requestUtil.js
lib/s3Helper.js
test/client/requestUtil.js

change limitResponse to a maxRecords number

---

.travis.yml
lib/api.proto
lib/api.proto.js
test/client/recordUtil.js

needed for https://github.com/brave/browser-laptop/issues/8024

Add hideInToolbar field to api.proto bookmarks

---

client/recordUtil.js
test/client/recordUtil.js

Fix #91
Also:
- Fix bug where recordUtil.resolveRecords() would mutate in-place.
- Improve human level of "Ignoring [record action] of object [1,2,3]" so it says the action string instead of number.
Bonus test plan:
1. `yarn dist` into browser-laptop
2. run browser-laptop and sync to the sync profile of #91:
```
squalider piccalilli mutate decomposability
waterily nonaligned watershed homeward
aidman tat nobleman filling
chromaticism copolymerizing prythee gonococci
```
3. confirm the bookmark folder "123456"
cc @SergeyZhukovsky

Same batch Create + Update records should resolve to Create

---

client/constants/messages.js
client/constants/proto.js
client/recordUtil.js
client/requestUtil.js
client/sync.js
lib/promiseHelper.js
test/client/recordUtil.js
test/client/requestUtil.js
test/promiseHelper.js

putConcurrency is configurable with ipc GOT_INIT_DATA.
Also deprecate SEND_SYNC_RECORDS category to be optional, defaulting to the record objectData.
Required for #112

Add requestUtil.bufferedPut to limit concurrency of put

---

client/recordUtil.js
test/client/recordUtil.js

Fix #130 
Test plan:
1. `yarn dist` into browser-laptop
2. change browser laptop appConfig to sync prod and join the sync profile from https://github.com/brave/sync/issues/130 on sync prod:
```
sulfuric operate wilfully poltergeist
balder playmate fica milt
unsettle headstrong madwoman compensatory
winteriest botcher giddying crustiest
```
3. after bookmarks download, there should be a Folder2 which contains Folder1.

Fix record resolution of Update bookmarks with site.title

---

client/recordUtil.js

It doesn't work in iOS <= 10.2
Related to #147

Don't use Object.values in recordUtil

---

client/recordUtil.js
client/sync.js
lib/api.proto.js
lib/serializer.js
lib/syncTypes.js
package.json
yarn.lock

handle sync PUT errors

---

client/config.js
client/constants/messages.js
client/requestUtil.js
client/sync.js
lib/s3Helper.js
server/lib/user-aws-credential-generator.js

Implemented a logic for SNS->SQS notifications.

Read data from notifications

---

client/config.js
client/constants/messages.js
client/requestUtil.js
client/sync.js
lib/s3Helper.js

- corrected interactions with laptop;
- corrected initial sync
- various small fixes

Various small notifications fixes

---

server/lib/user-aws-credential-generator.js
server/users.js

The credential server returns 200 no matter what, so errors due to
invalid credentials will propagate until protobufjs thorws an error.
This changes it to return 401 whenever credentials cannot be generated.
Test plan:
1. npm start
2. npm run browsertest (which is currently failing)
3. in the error messages, you should see '401 unauthorized' instead of
a protobuf error.

Better error messages from the credential server

---

client/init.js
client/sync.js

fix https://github.com/brave/sync/issues/221

Proprogate seed info to maybeSetDeviceId

---

lib/s3Helper.js

Changes to speed up polling new records

---

lib/s3Helper.js
test/client/requestUtil.js

fix https://github.com/brave/sync/issues/220

Add SQS test

---

package-lock.json

Generate package-lock.json by
1. modifying package.json in browser-launcher to have merge dep `^1.2.1`
2. delete merge folder in node_modules
3. npm install
4. make sure we have modified packge-lock.json
5. remove entire node_modules
6. do npm install and make sure we install merge version >= 1.2.1
7. npm audit should have no errors now
fix https://github.com/brave/sync/issues/232

Update merge to >=1.2.1

---

client/requestUtil.js
client/sync.js
lib/s3Helper.js
test/client/requestUtil.js

This fixes https://github.com/brave/browser-android-tabs/issues/925

Fixed receiving objects in chunk

---

client/requestUtil.js
lib/s3Helper.js

closes https://github.com/brave/sync/issues/277

Handled a situation where user has more than one backslash in id

---

package-lock.json

Resolves this warning (found via `npm audit`):
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ handlebars                                                   │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ istanbul [dev]                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
1 Update deps with `npm audit fix`
│ Path          │ istanbul > handlebars                                        │
├───────────────┼───────────────────────────────────────────────── …
```

Update deps with `npm audit fix`

---

lib/s3Helper.js

Sorting of records by timestamp was broken.
This PR particularly addresses https://github.com/brave/brave-browser/issues/3515 , it does not prevent re-appearing of records, but now as records will be provided sorted, then old parasite records will be neutralized by the new record.
In other words <...,CREATE, CREATE,...> or <...,DELETE, DELETE,...> or <...,UPDATE, UPDATE,...> safe. The only potential possibility of error is to have parasite records later than in the next request.

fix sorting

---

client/requestUtil.js

When the time or/and time zone on the client device is not correct, sync auth server rejects authentication with error 400/'Signed request body of the client timestamp is required.'. The clients can see only `Credential server response 400` . For the case when it is caused by time issue, this is passed to the client.
Fixes: https://github.com/brave/sync/issues/157 . 
Probably addresses:
https://github.com/brave/sync/issues/114
https://github.com/brave/sync/issues/212
https://github.com/brave/browser-android-tabs/issues/788

Check text on bad request status

---

package-lock.json

Helps fix brave/brave-browser#4075

Fix vulnerability preventing Desktop from building

---

client/recordUtil.js
test/client/recordUtil.js

This is revert of https://github.com/brave/sync/pull/313 .
It causes problem with this STR
```(Android, Android) <=> Core
1. Create chain Android1 <=> Android2
2. Create bookmarks on Android1:
wikipedia.com
espn.com
amazon.com
3. Wait untill bookmarks appear on Android2
4. Delete wikipedia.com from Android1
5. Wait untill bookmark will be deleted on Android2
6. Connect Core to chain
7.
Actual bookmarks:
wikipedia.com
espn.com
amazon.com
Expected bookmarks:
espn.com
amazon.com
```
With these STR brave-core logs show
```
get-existing-objects:
CREATE wikipedia.com
CREATE espn.com
CREATE amazon.com
DELETE wikipedia.com
resolve: all pairs with null
[1207:1207:0530/132313.432076:INFO:CONSOLE(1)] "Ignoring DELETE of object 93,212,16,154,213,179,21,41,212,0,57,255,12,41,120,72.", source: …
```

Revert PR#313 (Merge by id and action)

---

lib/s3Helper.js
test/client/requestUtil.js
test/s3Helper.js

There is a situation when sync lib sends duplicating records, first from S3 and then from SQS, it may happens if syncing bookmarks early after establishing a sync chain:
```
[26515:26515:0426/170809.283612:INFO:CONSOLE(5175)] "listObjects (1) S3 content.timestamp=1556287688729", source: chrome-extension://nomlkjnggnifocmealianaaiobmebgil/extension/brave-sync/bundles/bundle.js (5175)
[26515:26515:0426/170809.286318:INFO:CONSOLE(5175)] "listObjects (1) S3 content.timestamp=1556287688737", source: chrome-extension://nomlkjnggnifocmealianaaiobmebgil/extension/brave-sync/bundles/bundle.js (5175)
[26515:26515:0426/170908.000107:INFO:CONSOLE(5116)] "SQS record timestamp=1556287706300", source: chrome-extension://nomlkjnggnifocmealianaaiobmebgil/extension/brave-sync/bundles/bundle.js (5116) …
```

Ignore records from SQS which where seen in S3

---

client/requestUtil.js
lib/s3Helper.js
test/client/requestUtil.js

Create queues per device per categories.

Create separate queues for preferences records

---

package-lock.json
package.json

This resolves vulnerability with handlebars by removing the `coverage` task and dependency

Make istanbul optional. (STAGING)

---

package-lock.json
package.json

(It only gets downloaded when `npm run coverage` is ran)
Fixes https://github.com/brave/sync/issues/334

Make istanbul optional.

---

client/constants/messages.js
client/requestUtil.js
client/sync.js
lib/s3Helper.js
package-lock.json
package.json
test/client/requestUtil.js

fix #341 
fix #289
https://github.com/brave/brave-browser/issues/6552 will use this API to initiate the compaction

Compaction API

---

client/constants/messages.js
client/requestUtil.js
client/sync.js
test/client/requestUtil.js

This PR also prevents initiating new compaction process when there exists a compaction process running for a long time
also fix #351

Provide compaction complete/update callback

---

client/constants/messages.js
client/sync.js

fix https://github.com/brave/sync/issues/356
gives back full records when all records are successfully uploaded
or partial records/empty records when error occurred.

Add SENT_SYNC_RECORDS which is the callback of SEND_SYNC_RECORDS

---

client/constants/messages.js
client/init.js
client/requestUtil.js
client/sync.js
lib/api.proto
lib/api.proto.js
lib/crypto.js
lib/s3Helper.js
test/client/deviceIdV2.js
test/client/recordUtil.js
test/client/requestUtil.js

fix https://github.com/brave/sync/issues/333
This PR introduce device id v2 which is a 3 random bytes hex encoded string.
We also keep device id for backward compatibility.
Migration from existing device would be:
1. There will be extra `SAVE_INIT_DATA` for updating device id v2
2. Create new SQS queues using device id v2 and subscribe to old SQS queues created by device id
3. We will fetch from both queues for 24 hours and then delete the old queues

Introduce device id v2

---

client/constants/messages.js
client/init.js
client/requestUtil.js
client/sync.js
lib/api.proto
lib/api.proto.js
lib/crypto.js
lib/s3Helper.js
test/client/deviceIdV2.js
test/client/recordUtil.js
test/client/requestUtil.js

original PR https://github.com/brave/sync/pull/362

Introduce device id v2 (master)

---

.gitignore
client/constants/messages.js
client/requestUtil.js
client/sync.js
test/client/deviceIdV2.js
test/client/requestUtil.js

Related brave-browser issue https://github.com/brave/brave-browser/issues/7327 .
Related brave-core PR https://github.com/brave/brave-core/pull/4231 .

previousFetchTime parameter for FETCH_SYNC_RECORDS

---

client/init.js
client/recordUtil.js
client/requestUtil.js
client/sync.js
lib/s3Helper.js
lib/serializer.js
package-lock.json
package.json
server/lib/util.js
server/users.js
test/client/deviceIdV2.js
test/client/recordUtil.js
test/client/testHelper.js
test/testHelper.js

Partially fixes: https://github.com/brave/brave-browser/issues/8588

Update to fix npm vulnerabilities

---

client/init.js
client/recordUtil.js
client/requestUtil.js
client/sync.js
lib/s3Helper.js
lib/serializer.js
package-lock.json
package.json
server/lib/util.js
server/users.js
test/client/deviceIdV2.js
test/client/recordUtil.js
test/client/testHelper.js
test/testHelper.js

Fix problems flagged by `npm audit`
- `npm audit fix`
- manually updated standard (which had the acorn dependency)
- lint fixes
`staging` branch updated with https://github.com/brave/sync/pull/371

Update to fix npm vulnerabilities (uplift to master)

---

package-lock.json
package.json

Strategy attempted in https://github.com/brave/security/issues/101 caused complexities with `brave-core-crx-packager` (via `https-everywhere-updater`) unfortunately, through the tangled mess of dependencies ☹️ 
----------
Revert "Merge pull request #374 from brave/bsc-fix-npm-staging"
This reverts commit 2c33b6f9143858e5ec5c753c43a54fce4c376c04, reversing
changes made to 65e97ef9d29645281b3824f85f32bfaaf527f283.

Revert resolutions file entry fix for minimist (staging)

---

package-lock.json
package.json

Strategy attempted in https://github.com/brave/security/issues/101 caused complexities with `brave-core-crx-packager` (via `https-everywhere-updater`) unfortunately, through the tangled mess of dependencies ☹️ 
----------
Revert "Merge pull request #375 from brave/bsc-fix-npm"
This reverts commit f4b71bac02bde90178bf6b9c25c5d54e690a3c08, reversing
changes made to 4428f605acd31542387bfa8956dda28becaec650.

Revert resolutions file entry fix for minimist (master)

---

package-lock.json
package.json

Fixes brave/brave-browser#8722
NOTE: uses `optional-dev-dependency` to make the test runners "optional". The clean `package-lock.json` rebuild did not solve the issues there

Rebuild package-lock.json to fix npm audit errors

---

package-lock.json
package.json

Resolve `npm audit` problems by updating deps including forking/updating `optional-dev-dependency`
Helps fix https://github.com/brave/brave-browser/issues/9578

Resolve `npm audit` problems

---

package-lock.json
package.json

Resolve `npm audit` problems by updating deps including forking/updating `optional-dev-dependency`
Helps fix https://github.com/brave/brave-browser/issues/9578

Resolve `npm audit` problems (staging)
